import { LocalizationContent } from './src/types'

const content: LocalizationContent = {
    es: {
        home: 'Inicio',
        newGame: 'Nuevo Juego',
        released: 'Lanzamiento',
        game: 'Juego',
        searchGame: 'Buscar Juego',
        backlog: 'No jugado',
        inProgress: 'Jugando',
        played: 'Lo jugué',
        completed: 'Completado',
        wishList: 'Lista Deseos',
        summary: 'Resumen',
        metaScore: 'Puntuación',
        owned: 'Adquirido',
        hours: 'Horas',
        addNewGame: 'Agregar nuevo juego',
        close: 'Cerrar',
        delete: 'Borrar',
        update: 'Actualizar',
        save: 'Guardar',
        noSearchResults: 'No hay resultados',
        newGameName: 'Nombre del juego',
        noGamesDescription: 'Empieza añadiendo juegos a tu collección',
        gameSaved: 'Juego guardado',
        gameRemoved: 'Juego eliminado',
        welcome: 'Bienvenido'
    },
    en: {
        home: 'Home',
        newGame: 'New Game',
        released: 'Released',
        game: 'Game',
        searchGame: 'Search Game',
        backlog: 'Backlog',
        inProgress: 'In Progress',
        played: 'Played',
        completed: 'Completed',
        wishList: 'Wishlist',
        summary: 'Summary',
        metaScore: 'Metascore',
        owned: 'Owned',
        hours: 'Hours',
        addNewGame: 'Add New Game',
        close: 'Close',
        delete: 'Delete',
        update: 'Update',
        save: 'Save',
        noSearchResults: 'No search results',
        newGameName: 'Game name',
        noGamesDescription: 'Get started adding some games to your collection',
        gameSaved: 'Game Saved',
        gameRemoved: 'Game Removed',
        welcome: 'Welcome'
    }
}

export default content
